# -*- coding: utf-8 -*-
{
    "name": "Demandes de réapprovisionnement interne PrimeTech",
    "summary": "Gérez les demandes de réapprovisionnement interne et automatisez les transferts de stock.",
    "version": "18.0.1.1.0",
    "category": "Inventory/Inventory",
    "author": "PrimeTech",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock", "stock_account", "product", "web"],
    "data": [
        "security/replenishment_security.xml",
        "security/ir.model.access.csv",
        "data/replenishment_sequence.xml",
        "data/replenishment_activity.xml",
        "data/replenishment_mail_templates.xml",
        "report/replenishment_paperformat.xml",
        "report/replenishment_report.xml",
        "report/replenishment_templates.xml",
        "wizard/cancel_request_wizard_views.xml",
        "views/replenishment_request_line_views.xml",
        "views/replenishment_search_views.xml",
        "views/replenishment_request_views.xml",
        "views/replenishment_kanban_views.xml",
        "views/replenishment_activity_views.xml",
        "views/stock_picking_views.xml",
        "views/replenishment_dashboard_views.xml",
        "views/replenishment_config_settings_views.xml",
        "views/replenishment_menus.xml",
    ],
    "demo": [],
    "assets": {
        "web.assets_backend": [
            "primetech_replenishment_request/static/src/js/dashboard.js",
            "primetech_replenishment_request/static/src/xml/dashboard.xml",
        ],
    },
    "application": True,
    "installable": True,
}
