# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    "name": "Paie",
    "version": "18.0.3.4.0",
    "category": "Ressources humaines/Paie",
    "website": "https://github.com/OCA/payroll",
    "sequence": 38,
    "summary": "Gestion complète des bulletins, règles salariales et cotisations",
    "license": "LGPL-3",
    "author": "Odoo SA, Odoo Community Association (OCA)",
    "depends": [
        "account",
        "hr_contract",
        "hr_holidays",
        "mail",
        "web",
    ],
    "data": [
        "security/hr_payroll_security.xml",
        "security/ir.model.access.csv",
        "data/hr_payroll_sequence.xml",
        "data/hr_payroll_data.xml",
        "wizard/hr_payroll_contribution_register_report_views.xml",
        "wizard/hr_payroll_payslips_by_employees_views.xml",
        "views/menus.xml",
        "views/payroll_dashboard_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_payroll_structure_views.xml",
        "views/hr_salary_rule_category_views.xml",
        "views/hr_contribution_register_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_payslip_line_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/hr_employee_views.xml",
        "views/report_contributionregister.xml",
        "views/report_payslip.xml",
        "views/report_payslipdetails.xml",
        "report/report.xml",
        "views/res_config_settings_views.xml",
        "wizard/hr_payroll_send_email.xml",
        "wizard/hr_payslip_change_state_view.xml",
    ],
    "demo": ["demo/hr_payroll_demo.xml"],
    "assets": {
        "web.assets_backend": [
            "payroll/static/src/dashboard/payroll_dashboard.js",
            "payroll/static/src/dashboard/payroll_dashboard.xml",
            "payroll/static/src/dashboard/payroll_dashboard.scss",
        ],
    },
    "application": True,
    "maintainers": ["appstogrow", "nimarosa"],
}
